feat: UI support for invokedByDefault transformers
konveyor/move2kube-ui pull request #128
Opened 2022-09-23 17:45 UTC by kmehant

Signed-off-by: Mehant Kammakomati <kmehant@gmail.com>

2022-09-23 17:54 UTC, ashokponkumar submitted a review, later dismissed

2022-09-26 21:11 UTC, HarikrishnanBalagopal requested changes

2022-09-26 21:11 UTC, HarikrishnanBalagopal commented on src/app/projects/ProjectPlan.tsx
> +                                isDisabled={isPlanning}
Keep the variable name as `disableThisSection` and just define it as `const disableThisSection = isPlanning;` somewhere above.

2022-09-26 21:11 UTC, HarikrishnanBalagopal commented on src/app/projects/ProjectPlan.tsx
> +                                isDisabled={!props.project.status?.plan}
see above

2022-09-26 21:11 UTC, HarikrishnanBalagopal commented on src/app/projects/ProjectPlan.tsx
> +                    isDisabled={!props.project.status?.plan}
see above

2022-09-27 04:10 UTC, kmehant commented on src/app/qa/MultiLine.tsx
> +function MultiLine(props: IQAComponentProps): JSX.Element {
@HarikrishnanBalagopal  @ashokponkumar 
https://github.com/konveyor/move2kube-ui/pull/128/files#diff-9fbd7a7707d6fad02d98c83cc8c72a94821fa17a1983f54f1ef9c3da59bb1d25R113 

Its `MultiLineInput` in https://github.com/konveyor/move2kube/blob/main/types/qaengine/problem.go#L42 and `Multiline` in UI due to which multi line type questions breaking the QA engine at UI.

Weed need to decide whether following `MultiSelect` should we change this to `MultiLine` or change it to `MultiLineInput` which is there in move2kube code presently.

2022-09-27 04:11 UTC, kmehant commented on src/app/qa/MultiLine.tsx
> +function MultiLine(props: IQAComponentProps): JSX.Element {
In any case, this change is required for the QA engine not to break for multiline questions at UI

2022-09-27 06:37 UTC, HarikrishnanBalagopal commented on src/app/qa/MultiLine.tsx
> +function MultiLine(props: IQAComponentProps): JSX.Element {
This only changes the function name, it has zero impact in terms of what gets sent over the wire.

2022-09-27 06:53 UTC, kmehant commented on src/app/qa/MultiLine.tsx
> +function MultiLine(props: IQAComponentProps): JSX.Element {
Can you please check the completes changes?

2022-09-27 06:53 UTC, HarikrishnanBalagopal commented on src/app/qa/MultiLine.tsx
> +function MultiLine(props: IQAComponentProps): JSX.Element {
I see the issue https://github.com/konveyor/move2kube/blob/main/types/qaengine/problem.go#L42
currently has `MultiLineInput` and the QA Wizard https://github.com/konveyor/move2kube-ui/blob/main/src/app/qa/QAWizard.tsx#L113 has `Multiline`

The only change required is to change https://github.com/konveyor/move2kube-ui/blob/main/src/app/qa/QAWizard.tsx#L113 to `MultiLineInput` to match the CLI. It also makes it similar to `Input` we already have. https://github.com/konveyor/move2kube-ui/blob/main/src/app/qa/QAWizard.tsx#L111

2022-09-27 06:54 UTC, kmehant commented on src/app/qa/MultiLine.tsx
> +function MultiLine(props: IQAComponentProps): JSX.Element {
But by the semantic meaning `Input` can be anything.

2022-09-27 06:55 UTC, kmehant commented on src/app/qa/MultiLine.tsx
> +function MultiLine(props: IQAComponentProps): JSX.Element {
Why not`MultiSelectInput` 🤔

2022-09-27 07:26 UTC, kmehant commented
@HarikrishnanBalagopal Made the changes, please review!

2022-09-27 07:32 UTC, kmehant commented
fixes https://github.com/konveyor/move2kube-ui/issues/129

2022-09-27 07:48 UTC, HarikrishnanBalagopal approved these changes
LGTM

2022-09-27 08:30 UTC, merged